template: true   # required for local templates
valuesFilePath: ./values.yml

resources:
  - name: mvn_repo
    type: GitRepo
    configuration:
      path: {{ .Values.repoPath }}
      gitProvider: {{ .Values.gitProvider }}

  - name: mvn_build_info
    type: BuildInfo
    configuration:
      sourceArtifactory: {{ .Values.artifactory }}
      buildName: $res_mvn_build_info_buildName
      buildNumber: $res_mvn_build_info_buildNumber


pipelines:
  - name: demo_maven
    steps:
      - name: mvn_build_step
        type: MvnBuild
        configuration:
          mvnCommand: clean install -DskipTests -DskipITs
          autoPublishBuildInfo: true
          deployerSnapshotRepo: {{ .Values.deployerSSRepo }}
          deployerReleaseRepo: {{ .Values.deployerRelRepo }}
          inputResources:
            - name: mvn_repo
          integrations:
            - name: {{ .Values.artifactory }}
          outputResources:
            - name: mvn_build_info

      - name: publish_build
        type: PublishBuildInfo
        configuration:
          forceXrayScan: true
          inputSteps:
            - name: mvn_build_step
          outputResources:
            - name: mvn_build_info
